[project]
name = "mas-orchestrator"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "argparse",
    "datasets",
    "groq",
    "openai",
    "together",
    "python-dotenv",
    "pandas",
    "openpyxl",
    "ray[default]>=2.10",
    "torch>=2.4.0",
    "numpy",
    "tensordict==0.6.2",
    "transformers",
    "accelerate",
    "verl",
    "cachesaver"
]

[tool.uv.sources]
verl = { path = "./verl", editable = true }